name: Flask App deployed


on:
#  push:
#  branches: [mywork]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted


    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: setup docker compose on runner 
        run: docker/setup-compose-action@v2
          
      - name: deploy with docker compose
        run: docker compose up -d --build
