name: Flask App deployed

on:
  push:
    branches: [mywork]
  
  workflow_dispatch:


jobs:
  deploy:
    env:
      DOCKERHUB_USER : ${{ vars.DOCKERHUB_USER }}
    runs-on: self-hosted


    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: setup docker compose on runner 
        uses: docker/setup-compose-action@v2
          
      - name: deploy with docker compose
        run: docker compose up -d --build
