name: CICD

on:
  workflow_dispatch:
    input:                                                        # We can define the input to run the pipeline for env
      environment:                                                # Define environment type and its option inside this block
        discription: This is the environment value we can choose for pipline
        default: 'dev'                                            # we have taken default env is as a dev
        required: true                                            # True 
        type: choice                                              # Here we have taken type as a choice, we can also use boolen, env and so on.
        options:                                                  # The options we have
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from GitHub
        run: echo "Code clone from GitHub"
  


  build:
    needs: [code]                                                   # Work as like depends-on so here build needs test to run first
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "Docker container build"

  test:
    needs: [build]                                                  # Work as like depends-on so here test needs build to run first
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Testing the code"

  deploy:
    needs: [test, build]                                            # Work as like depends-on so here deploy needs test and build to run first
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "Code has been successfully deployed"
