# This will Deploy the safe & ensure, Tested app to deploy on server
#

name: Deploy To Server

on:
  workflow_call:


jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: ${{ github.sha }}

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: ssh to prod server and create app folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEYS }}
          script: |
            echo " Installing requried packages & Folders "
            sudo apt update && sudo apt install docker.io docker-compose-v2 -y
            sudo usermode -aG docker $USER
            mkdir -p devops


      - name: Copy the docker compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEYS }}
          source: docker-compose.yml
          target: ~/devops


      - name: ssh to prod server and run the app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEYS }}
          script: |
            echo "Running App"
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ github.sha }}
            echo ${{ secrets.DOCKERHUB_TOEKN }} | docker login --user ${{ vars.DOCKERHUB_USER }} --password-stdin
            cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
