<<<<<<< HEAD
# This is workflow name
name: Hello 

# runs on an automatic trigger, whenever change is pushed to branch (deployment)
on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - '**.html'

  pull_request:
    branches: [main]

# these are jobs inside the workflow
jobs:

  # this is the name of the job
  greet:
    # this is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
=======
name: Hello

on:
  push:
    branches: [main]



jobs:


  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello My World"
>>>>>>> fde780a (Added github and workflow folder also added first yml file hello.yml)

      - name: say hello to username
        run: echo "Hello $USER"

<<<<<<< HEAD
  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version
=======

  
>>>>>>> fde780a (Added github and workflow folder also added first yml file hello.yml)
