name: Hello

on:
  push:
    branches: [main]



jobs:


  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello My World"

      - name: say hello to username
        run: echo "Hello $USER"
 


  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show the version for Python and Docker
        run: docker --version && python --version && cat /etc/os-release

